name: kronius
author: lightPlugins
version: 1.0
main: de.lightPlugins.kronius.organisation.Main
api-version: 1.17
softdepend: []
#load: STARTUP
#loadbefore: [XCore, SkyblockX]
commands:
  kronius:
  stones: